{ ... }:
{
  programs.starship = {
    enable = true;
    # Automatically integrate with Zsh (enabled by default, included here for clarity)
    enableZshIntegration = true;

    # The plain-text-symbols.toml is generated by `starship preset plain-text-symbols`
    # See README.md for more details
    settings = (builtins.fromTOML (builtins.readFile ./plain-text-symbols.toml)) // {
      add_newline = false;
    };
  };
}
